### ISSUE TITLE
🐛 버그 수정 : 기본 칵테일 관리 기능 - 기본 칵테일 조회 기능 버그 수정

### ISSUE THREAD

**Issue by YoungH66** [ToastitProject/toastit_v2_back#15]
### 현재 기본 칵테일 검색 기능에 버그가 존재함.
 - 재료만으로 구성된 keyword는 정상 작동함
 - 알코올 유무가 포함된 keyword에서 문제가 발생함.
   -  알코올 / 논알콜 의 keyword가 AlcoholType이 아니라 SearchType으로 인식되는 버그
   - AlcoholType의 검색 조건을 알코올/알콜, 논알코올/논알콜/무알코올/무알콜 로 확장해야 함. 현재 test로 사용하는 db에 "무알콜" 이라고 적재되어 있음.
     - 또한, 드물게 필드값이 "알코올 / 무알콜" 이라고  되어있는 경우도 있어서, 차후 db에 적재되는 데이터를 수정해야 함. 

## ✔️ TO-DO
- [x] 알코올 유무 단일 검색 기능 수정
- [x] 알코올 유무 포함 복합 검색 기능 수정
- [x] 알코올 유무 검색 키워드 확장
- [ ] 데이터셋 수정(차후 예정)

**Comment by YoungH66** [comment]
해당 이슈 수정했습니다.
- 알코올 유무 단일 검색 기능이 수정되었습니다.
- 알코올 유무와 재료의 복합 검색 기능이 수정되었습니다.
- 알코올 유무 검색 키워드를 확장했습니다.
  - 알코올 -> 알콜, 알코올
  - 무알콜 -> 무알콜, 무알코올, 논알콜, 논알코올
- 알코올 / 무알콜 의 경우 그대로는 사용하지 못하지만, 양쪽의 검색 결과에 포함하도록 조치하였습니다.
