### ISSUE TITLE
✨ 새 기능 : 회원가입, 로그인, 로그아웃 및 사용자 정보 관리 기능 구현

### ISSUE THREAD

**Issue by rowing0328** [ToastitProject/toastit_v2_back#4]
## 📄 작업 내용
- 사용자 정보를 처리하고 반환하는 작업입니다. 
- 로그인한 사용자의 정보를 조회하여 반환하는 API를 작성합니다. 
- 이를 통해 시스템에서 사용자의 데이터를 관리하고, 이를 클라이언트에게 효율적으로 전달할 수 있도록 합니다.
- 마이페이지 기능 추가:
  - 닉네임 중복 체크 및 변경 기능 구현
  - 비밀번호 변경 기능 구현
  - 임시 회원 탈퇴 기능 구현
  - 프로필 이미지 변경 기능 주석 처리 (추후 구현 예정)
  - 사용자 정보 수정 기능에 대한 예외 처리 및 응답 메시지 추가

## ✔️ TO-DO
- [x] 사용자 정보 처리 기능 구현 (UserEntity 및 User 모델 사용)
- [x] 로그인한 유저의 정보를 반환하는 UserController 작성
- [x] UserRepository와 UserService를 통해 사용자 정보 조회 기능 구현
- [x] UserResponse DTO를 사용하여 사용자 정보 클라이언트 전달
- [x] JpaUserRepository를 활용한 데이터베이스 연동
- [x] 회원가입 기능 구현 (이메일, 닉네임, 비밀번호 등록)
- [x] 로그인 기능 구현 (이메일 및 비밀번호를 통한 인증)
- [x] 로그아웃 기능 구현 (JWT 토큰 무효화 또는 삭제)
- [x] 닉네임 중복 체크 및 변경 기능 구현
- [x] 비밀번호 변경 기능 구현
- [x] 임시 회원 탈퇴 기능 구현
- [x] 프로필 이미지 변경 기능 주석 처리 (추후 구현 예정)
