### ISSUE TITLE
✨ 새 기능 : 기본 칵테일 관리 기능 구현

### ISSUE THREAD

**Issue by YoungH66** [ToastitProject/toastit_v2_back#9]
## 📄 작업 내용
- 프로젝트의 기본적인 기능인 기본 칵테일 관리 기능을 구현합니다.
- 사용자가 요청한 기능에 대한 결과를 반환하는 API를 작성합니다.
- 사용자는 기본으로 제공하는 칵테일의 정보를 검색하고 정보를 얻을 수 있도록 합니다.
- 기본 칵테일 관리 기능 추가:
  - 기본 칵테일 전체 리스트 탐색 기능 구현
  - 기본 칵테일 상세 정보 열람 기능 구현
  - 기본 칵테일 검색 기능 구현
  - 칵테일 재료에 대한 상세 정보 열람 기능 구현 (추후 구현 예정)
 - 미구현된 기능을 추가할 예정입니다.
   - 칵테일 등록 기능
   - 칵테일 상세 조회 기능
   - 칵테일 ID 검색 기능
- mongodb 빈이 중복되는 이슈가 존재합니다. 빠르게 수정 예정입니다.
- 테스트 코드를 추가할 예정입니다.
- domain에 record 클래스 도입 검토 예정입니다.

## ✔️ TO-DO
- [ ] 기본 칵테일 레시피 db에 적재
- [x] 테스트용 칵테일 레시피 db에 적재
- [x] 기본 칵테일 전체 리스트 탐색 기능 구현
- [x] 적정 갯수마다 페이징 처리 (예정)
- [x] 기본 칵테일 상세 정보 열람 기능 구현
- [x] 기본 칵테일 통합 검색 기능 구현
- [ ] 칵테일 재료에 대한 상세 정보 열람 기능 구현 (추후 구현 예정)
- [ ] 주석처리

**Comment by YoungH66** [comment]
TO-DO 재설정
 - 1. 기본 칵테일 레시피는 기존 v1에 쓰던 데이터가 아닌 새로운 데이터를 사용할 예정
 - 2. 기본 칵테일 상세 정보 열람 기능은 구현된 기능중 id를 통한 검색을 통해 구현할 수 있다고 판단됨. 프론트와 미팅 이후 수정
 - 3. 칵테일 재료에 대한 상세 정보 열람 기능은 재료에 대한 새로운 db를 구축하는 방향으로 진행
 - 4. 주석은 남은 기능 개발 이후에 전체적으로 진행 예정

**Comment by YoungH66** [comment]
중요 기능의 구현이 완료되었으며, 데이터베이스를 마이그레이션 할 예정이기 때문에 해당 issue를 닫음.
